[package]
authors = ["Simon Repp <simon@fdpl.io>"]
edition = "2018"
name = "faircamp"
version = "0.1.0"

[dependencies]
bincode = "1.3.2"
chrono = { features = ["serde"], version = "0.4.19" }
clap = { features = ["derive"], version = "3.0.10" }
claxon = "0.4.3"
enolib = { git = "https://codeberg.org/simonrepp/enolib-rs" }
hound = "3.4.0"
id3 = "0.6.1"
indoc = "1.0.3"
iso_currency = "0.4.1"
lewton = "0.10.2"
metaflac = "0.2.4"
nanoid = "0.3.0"
pulldown-cmark = "0.8.0"
rmp3 = { features = ["float", "simd"], version = "0.3.1" }
serde = "1.0.125"
serde_derive = "1.0.125"
slug = "0.1.4"
url = "2.2.1"
zip = { features = ["deflate"], version = "0.5.11" }
