[package]
authors = ["Simon Repp"]
edition = "2021"
name = "faircamp"
version = "0.1.0"

[dependencies]
bincode = "1.3.3"
chrono = { features = ["serde"], version = "0.4.21" }
clap = { features = ["derive"], version = "3.2.16" }
claxon = "0.4.3"
enolib = { git = "https://codeberg.org/simonrepp/enolib-rs" }
hound = "3.4.0"
id3 = "1.3.0"
indoc = "1.0.7"
iso_currency = "0.4.3"
lewton = "0.10.2"
libvips = "1.4.3"
metaflac = "0.2.5"
nanoid = "0.4.0"
ogg = "0.9.0"
opus = "0.3.0"
pulldown-cmark = "0.9.2"
rmp3 = { features = ["float", "simd"], version = "0.3.1" }
serde = "1.0.143"
serde_derive = "1.0.143"
slug = "0.1.4"
url = "2.2.2"
webbrowser = "0.7.1"
zip = { features = ["deflate"], version = "0.6.2" }
