[package]
authors = ["Simon Repp"]
edition = "2021"
name = "faircamp"
version = "0.9.2"

[build-dependencies]
enolib = { git = "https://codeberg.org/simonrepp/enolib-rs", tag = "0.3.0" }
indoc = "2.0.3"
pulldown-cmark = { default-features = false, features = ["simd"], version = "0.9.3" }
slug = "0.1.4"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.4.0"
base64 = "0.21.5"
bincode = "1.3.3"
chrono = { features = ["serde"], version = "0.4.31" }
clap = { features = ["derive"], version = "4.4.7" }
claxon = "0.4.3"
enolib = { git = "https://codeberg.org/simonrepp/enolib-rs", tag = "0.3.0" }
hound = "3.5.1"
id3 = "1.9.0"
image = { optional = true, version = "0.24.7" }
indoc = "2.0.4"
iso_currency = "0.4.4"
lewton = "0.10.2"
libvips = { optional = true, version = "1.5.1" }
metaflac = "0.2.5"
nanoid = "0.4.0"
ogg = "0.9.0"
opus = "0.3.0"
opus_headers = "0.1.2"
pacmog = "0.4.1"
pulldown-cmark = { default-features = false, features = ["simd"], version = "0.9.3" }
rmp3 = { features = ["float", "simd"], version = "0.3.1" }
sanitize-filename = "0.5.0"
serde = "1.0.190"
serde_derive = "1.0.190"
slug = "0.1.4"
tokio = { features = ["macros", "rt-multi-thread"], version = "1.33.0" }
url = "2.4.1"
webbrowser = "0.8.12"
zip = { features = ["deflate"], version = "0.6.6" }

[features]
image = ["dep:image"]
libvips = ["dep:libvips"]
