[package]
authors = ["Simon Repp <simon@fdpl.io>"]
edition = "2021"
name = "faircamp"
version = "0.1.0"

[dependencies]
bincode = "1.3.3"
chrono = { features = ["serde"], version = "0.4.19" }
clap = { features = ["derive"], version = "3.0.10" }
claxon = "0.4.3"
enolib = { git = "https://codeberg.org/simonrepp/enolib-rs" }
hound = "3.4.0"
id3 = "1.0.2"
indoc = "1.0.3"
iso_currency = "0.4.2"
lewton = "0.10.2"
metaflac = "0.2.5"
nanoid = "0.4.0"
pulldown-cmark = "0.9.1"
rmp3 = { features = ["float", "simd"], version = "0.3.1" }
serde = "1.0.133"
serde_derive = "1.0.133"
slug = "0.1.4"
url = "2.2.2"
zip = { features = ["deflate"], version = "0.5.13" }
