[package]
authors = ["Simon Repp <simon@fdpl.io>"]
edition = "2018"
name = "faircamp"
version = "0.1.0"

[dependencies]
bincode = "1.3.2"
chrono = { features = ["serde"], version = "0.4.19" }
clap = { features = ["std"], git = "https://github.com/clap-rs/clap/" }
enolib = { path = "enolib" }
id3 = "0.6.1"
indoc = "1.0.3"
iso_currency = "0.4.0"
metaflac = "0.2.4"
nanoid = "0.3.0"
pulldown-cmark = "0.8.0"
rmp3 = "0.3.1"
serde = "1.0.123"
serde_derive = "1.0.123"
slug = "0.1.4"
url = "2.2.1"
zip = { features = ["deflate"], version = "0.5.11" }
