[package]
authors = ["Simon Repp"]
edition = "2021"
name = "faircamp"
version = "0.1.0"

[build-dependencies]
indoc = "1.0.8"
pulldown-cmark = "0.9.2"
slug = "0.1.4"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
base64 = "0.21.0"
bincode = "1.3.3"
chrono = { features = ["serde"], version = "0.4.24" }
clap = { features = ["derive"], version = "4.2.1" }
claxon = "0.4.3"
enolib = { git = "https://codeberg.org/simonrepp/enolib-rs" }
hound = "3.5.0"
id3 = "1.6.0"
indoc = "2.0.1"
iso_currency = "0.4.3"
lewton = "0.10.2"
libvips = "1.5.1"
metaflac = "0.2.5"
nanoid = "0.4.0"
ogg = "0.9.0"
opus = "0.3.0"
opus_headers = "0.1.2"
pacmog = "0.4.1"
pulldown-cmark = "0.9.2"
rmp3 = { features = ["float", "simd"], version = "0.3.1" }
sanitize-filename = "0.4.0"
serde = "1.0.159"
serde_derive = "1.0.159"
slug = "0.1.4"
tokio = { features = ["macros", "rt-multi-thread"], version = "1.27.0" }
url = "2.3.1"
webbrowser = "0.8.8"
zip = { features = ["deflate"], version = "0.6.4" }
